apiVersion: v1
kind: Service
metadata:
  name: python-12factor-service
spec:
  selector:
    app: python-12factor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort